
version: '3.8'

services:
  mysql_NGNIX:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: pokemons
      MYSQL_ROOT_PASSWORD: Pa$$w0rd
      MYSQL_USER: user
      MYSQL_PASSWORD: Pa$$w0rd




    ports:
      - "3306:3306"
    volumes:
      - ./mysql_NGNIXb/my.cnf:/etc/mysql/my.cnf



      
  nginx:
    image: nginx:lastest
  wordpress:
    depands_on:
      -  db
    image: wordpress:lastest
    ports:
      -  '8000:80'
   restart: always
   environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_DB_NAME: wordpress


